"""Add BuildUnit table.

Revision ID: 028688a5e692
Revises: 
Create Date: 2018-02-14 18:35:26.083540+00:00

"""
from alembic import op
import sqlalchemy as sa
import bcpc_build.db.migration_types
import uuid


# revision identifiers, used by Alembic.
revision = '028688a5e692'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('build_unit',
    sa.Column('id', bcpc_build.db.migration_types.UUIDType(), nullable=False,
              default=uuid.uuid4),
    sa.Column('build_dir', sa.Unicode(length=200), nullable=False),
    sa.Column('build_user', sa.Unicode(length=64), nullable=False),
    sa.Column('description', sa.Unicode(length=200), nullable=True),
    sa.Column('name', sa.Unicode(length=128), nullable=False),
    sa.Column('source_url', sa.Unicode(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('build_unit')
    # ### end Alembic commands ###
