"""Add timestamp metadata to build unit.

Revision ID: c45328521706
Revises: 028688a5e692
Create Date: 2018-03-14 21:01:10.174786+00:00

"""
from alembic import op
from datetime import datetime
import sqlalchemy as sa
import bcpc_build.db.migration_types


utcnow = datetime.utcnow
# revision identifiers, used by Alembic.
revision = 'c45328521706'
down_revision = '028688a5e692'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('build_unit', sa.Column('created_at',
        sa.TIMESTAMP(timezone=True), nullable=True, default=utcnow))
    op.add_column('build_unit', sa.Column('updated_at',
        sa.TIMESTAMP(timezone=True), nullable=True, default=utcnow,
        onupdate=utcnow))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('build_unit', 'updated_at')
    op.drop_column('build_unit', 'created_at')
    # ### end Alembic commands ###
